services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    ports:
      - 3004:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - "start-dev"
    volumes:
      - ./local/keycloak/prod/:/opt/jboss/keycloak/standalone/data/
  backend:
    build: .
    ports:
    - 8080:8080
    depends_on:
      - keycloak